name: CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**/*.yml
      - .gitignore
      - LICENSE
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - .github/**/*.yml
      - .gitignore
      - LICENSE
      - README.md

jobs:
  validate:
    name: Validate and Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.4

      - name: Initialise with no backend
        run: terraform init -backend=false

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Validate the configuration
        run: terraform validate
  scan:
    name: Scan with tfsec
    needs: validate
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF artifact
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
